apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app}
spec:
  template:
    spec:
      containers:
      - name: ${app}
        volumeMounts:
        - name: config-properties-volume
          readOnly: true
          mountPath: /home/app/${app}/conf
      volumes:
      - name: config-properties-volume
        configMap:
          name: ${app}-config-properties