apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${app}
spec:
  selector:
    matchLabels:
      app: ${app}
  serviceName: ${app}
  replicas: 3
#  ordinals:
#    start: 100
  template:
    metadata:
      labels:
        app: ${app}
    spec:
      enableServiceLinks: false
      containers:
      - name: ${app}
        image: ${app}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
